apiVersion: paas.github.com/v1
kind: ReplicasDemo
metadata:
  name: replicasdemo-sample
spec:
  # TODO(user): Add fields here
  batchSize: 1
  deploymentSpec:
    replicas: 3
    selector:
      matchLabels:
        tier: replicasdemo-sample
    template:
      metadata:
        labels:
          tier: replicasdemo-sample
      spec:
        containers:
          - name: php-redis
            image: gcr.io/google_samples/gb-frontend:v3
