# ======= 服务 =======
services:
  # 服务名
  - name: quaint-opa
    # 用于联系服务的基本url
    url: https://example.com/control-plane-api/v1
    credentials:
      bearer:
        token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"

# 标签, opa上传决策日志和状态信息时会包含标签
labels:
  app: quaint-opa
  region: west
  environment: production

bundles:
  authz:
    # 用于联系远程服务器的服务名称。
    service: quaint-opa
    # 用于从配置的服务下载包的资源路径。
    resource: bundles/http/example/authz.tar.gz
    # 包持久化到磁盘
    persist: true
    polling:
      # bundle 下载等待的最短时间。
      min_delay_seconds: 300
      # bundle 下载等待的最长时间。
      max_delay_seconds: 600

# 决策日志
decision_logs:
  service: quaint-opa
  # partition_name为区分上传地址,会跟到 /logs 后, 即：
  # http://demo-server:8888/logs/bundle
  # 注意上传的是gzip日志文件
  partition_name: bundle
  reporting:
    min_delay_seconds: 300
    max_delay_seconds: 600

# 状态
status:
  # 用于联系远程服务器的服务名称
  service: quaint-opa
  # 即 http://demo-server:8888/status/bundle
  partition_name: bundle

# 默认决策路径
default_decision: /http/example/authz/allow
